# Generated by Django 4.2.4 on 2023-09-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homework2app', '0005_alter_product_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_quantity',
            field=models.IntegerField(),
        ),
    ]
